config/routes.rb
Blog16::Application.routes.draw do
	
  resources :user_actions 
  resources :posts  
  resources :comments

  devise_for :views

  devise_scope :user do 
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  devise_for :users

  resources :ucs

  root :to => 'posts#index'

end

app/controllers/ucs_controller.rb
class UcsController < ApplicationController
	
  before_filter :authenticate_user!  
  before_filter :find_user,                   only: [:show,:edit,:update, :destroy]
  before_filter :allow_only_admins,           only: [:index,:edit,:update, :destroy]
  after_filter  :log_user_action_for_update,  only:  :update
  after_filter  :log_user_action_for_destroy, only:  :destroy
  def index
    @users = User.all
    @posts = Post.order("created_at DESC").includes(:user)
  end
  
  def show
    unless  @user 
    render_404
    end  	    
  end
  
 # def new
  #  @user = User.new
  #end
  
  def edit
  end
  
  #def create 
    #render text: params.inspect
   # @user = User.create(params[:user])
    #if @user.errors.empty?
     # redirect_to uc_path(@user)
    #else
     # "new"
    #end
  #end
  
  def update
    @previous_login = @user.login
    @previous_role  = @user.role
    @user.update_attributes(params[:user])
    if @user.errors.empty?
      redirect_to ucs_path(@user)
    else
      "edit"
    end
  end
  
  def destroy
    @user.destroy
    redirect_to action: "index"
  end
  
  private 
  
  def find_user
    @user = User.where(id: params[:id]).first
    render_404 unless @user
    
  end
  
  def log_user_action_for_update
    @user_presence = true
    if current_user && ( current_user.role == "admin" )
      UserAction.create(
        user: current_user, 
        description: 
      	        "Controller: #{params[:controller]} || Action: #{params[:action]} || email: #{@user.email} || Previous_Login: #{@previous_login}  || Login: #{@user.login} || Previous_Role: #{@previous_role} || Role: #{@user.role}"
    )
    end
  end
  
  def log_user_action_for_destroy
    @user_presence = false
    if current_user && ( current_user.role == "admin")
      UserAction.create(
        user: current_user, 
        description: 
      	        "Controller: #{params[:controller]} || Action: #{params[:action]} || email: #{@user.email} || Login: #{@user.login} || Role: #{@user.role}"
    )
    end
  end
  
  
  
end

app/helpers/uc_helper.rb
module UcHelper
end

app/views/ucs/edit.html.haml
%h1 Edit new user
= form_for @user, :url => { action: "update" } do |f|
  %p
    Login:
    = f.text_field :login
  = select(:user, :role, [['admin'], ['moderator'], [nil]])
  %p= f.submit "Update user"

app/views/ucs/index.html.haml
%h1 Users
- if @users.empty?
  %b No users
- else
  
  %table{ border: "1" }
    %tr
      %th User id
      %th email
      %th Login
      %th Role
      %th{:style => "text-align:left;"} Created at
      %th
    - @users.each do |u|
      %tr
        %td= u.id
        %td= u.email
        %td
          = link_to u.login, uc_path(u)
        %td= u.role
        %td= u.created_at
        %td= link_to 'Edit', edit_uc_path(u)
        %td= link_to "Delete", uc_path(u), method: :delete, data:{confirm: |
        "Do you really want to delete user?"}                         |
  

app/views/ucs/new.html.erb
%h1 Create new user
= form_for @user, :url => { action: "create" } do |f|
  %p
    Login:
    = f.text_field :login
  %p= f.submit "Create user"





app/views/ucs/new.html.haml
%h1 Create new user
= form_for @user, :url => { action: "create" } do |f|
  %p
    Login:
    = f.text_field :login
  %p= f.submit "Create user"





app/views/ucs/show.html.haml
%h1= @user.login
%ul
  %li
    email: #{@user.email}
  %li
    login: #{@user.login}
  %li
    Role: #{@user.role}