config/routes.rb
Blog16::Application.routes.draw do
	
  resources :user_actions 
  resources :posts  
  resources :comments

  devise_for :views

  devise_scope :user do 
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  devise_for :users

  resources :ucs

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  validates :title, :presence => true,
  :length => { :minimum => 3 }
  attr_accessible :author, :content, :title
  belongs_to :user
  has_many   :comments, :dependent => :destroy
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!,                                            except: [:index]
  before_filter :find_post,                                                     only:   [:destroy, :update, :edit, :show]
  before_filter :allow_only_admins_moderators_and_authors_to_posts,             only:   [:update, :edit, :destroy]
  after_filter  :log_user_action_for_posts,                                     only:   [:create, :update, :destroy]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at DESC").includes(:user)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    old = @post.comments.includes(:user)
    sort_comments_in_tree old
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
   end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    
    @previous_content = @post[:content]
    respond_to do |format|
      if @post.update_attributes(params[:post])
      	
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
        
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @previous_content = @post.content 
    @post.destroy
    
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
  
  
  def edit_comment(params)
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end
  
  def update_comment(params)
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.update_attributes(params[:comment])
    redirect_to post_path(@post)
    
  end
  
  
  private
  
    def allow_only_admins_moderators_and_authors_to_posts
      if @post.user != current_user && current_user.role.nil? 
      	render_403
      end
    end
    
    def find_post
      @post = Post.where(id: params[:id]).first
      render_404 unless @post 
    end
    
    def log_user_action_for_posts
    @user_presence = true
    if current_user && ( current_user.role == "admin" || current_user.role == "moderator" )
      UserAction.create(
        user: current_user, 
        description: log_description(params[:action])
      )
      end
    end
    

    
   def log_description(x)
     if x == "create"
       return "Controller: #{params[:controller]} || Action: #{params[:action]} || Id: #{@post.id} || Text: #{@post.content}"
     end
     if x == "update"
       return "Controller: #{params[:controller]} || Action: #{params[:action]} || Id: #{@post.id} || Previous_Text: #{@previous_content} || Text: #{@post.content}"
     end
     if x == "destroy"
       return "Controller: #{params[:controller]} || Action: #{params[:action]} || Id: #{@post.id} || Text: #{@post.content}"
     end
     
   end
    
    
    
    
  
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :content
    %br/
    = f.text_area :content
  .actions
    = f.submit

app/views/posts/edit.html.haml
%h1 Editing post
= render 'form'
= link_to 'Show', @post
|
\#{link_to 'Back', posts_path}

app/views/posts/index.html.haml
%h1 Listing posts

- @posts.each do |post|
  .post
    .title
      .postInfo
        %h2= post.title.prep.break_long_words
        = link_to post.user.login, uc_path(post.user)
      .links
        -if current_user 
          =link_to 'Show', post_path(post)
        - if current_user && ( post.user == current_user || ( current_user.role == "admin" || current_user.role == "moderator" ) )
          = link_to 'Edit', edit_post_path(post)
          = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
      .push  
    .content= post.content.prep.break_long_words
  
= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post
= render 'form'
= link_to 'Back', posts_path

app/views/posts/show.html.haml
%h2= @post.title
%p=  @post.content

.post
  .title
    .postInfo
      %h2= @post.title.prep.break_long_words
      = link_to @post.user.login, uc_path(@post.user)
    .links
      - if current_user && ( @post.user == current_user || ( current_user.role == "admin" || current_user.role == "moderator" ) )
        = link_to 'Edit', edit_post_path(@post)
        = link_to 'Destroy', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }
    .push  
  .content= @post.content.prep.break_long_words

%h3  Comments
%p{:style => "color: green;"}= flash[:success]
%p{:style => "color: red;"}= flash[:error]
- @comments.each do |comment|
  .comment{ style: "margin-left: #{comment.level}em" }
    .links
      .left
        = link_to comment.user.login, uc_path(comment.user)
        - if comment.comment_id 
          to #{ link_to comment.comment.user.login, uc_path(comment.comment.user)}
        - else 
          to Post
      .right
        %span.createComment{ "data-comment_id" => comment.id } Reply
        - if comment.user == current_user || ( current_user.role == "admin" || current_user.role == "moderator" )
          %span.editComment{ "data-comment_id" => comment.id } Edit 
          = link_to 'Destroy', comment_path(comment), :confirm => 'Are you sure?',:method => :delete
          
      .push     
    .body{ id: "comment_#{comment.id}"}= comment.body
    
%h2 Add a comment:
= form_for(@post.comments.build(post: @post)) do |f|
  = f.hidden_field :post_id
  .field
    = f.label :body
    %br/
    = f.text_area :body, maxlength:50
  .actions
    = f.submit
%br/

= form_for(@post.comments.build(post: @post), html: {id: "comment_with_parent_form"}) do |f|
  = f.hidden_field :comment_id
  = f.hidden_field :post_id
  .field
    = f.label :body
    %br/
    = f.text_area :body, maxlength:50
  .actions
    = f.submit
%br/
= form_for(@post.comments.build(post: @post), html: {id: "edit_comment_form"}) do |f|
  %input{ "name"=> "_method", "type" => "hidden", "value" => "put" }
  .field
    = f.label :body
    %br/
    = f.text_area :body, maxlength:50
  .actions
    = f.submit "Save"
%br/
= link_to 'Edit Post', edit_post_path(@post)
|
\#{link_to 'Back to Posts', posts_path} |

